.github/workflows/deploy.yml
.gitlab-ci.yml

Prepre for mirroring to gitlab

---

.github/workflows/deploy.yml
.gitlab-ci.yml

sync develop to main cos main is a bit beyond

sync develop

---

public/locales/en/translations.json
src/components/Event/EventWithKids.tsx
src/components/Event/index.css
src/pages/Subpage.tsx

close [gitlab issue #67](https://gitlab.com/need4deed/website/-/issues/67)

67 new event page workshop for volunteering with kids only english version

---

src/components/Event/EventWithKids.tsx
src/components/Event/index.css

Fix  event mobile styling

---

src/components/forms/validators.ts
src/config/constants.ts

1. remove base64 scrambled email domains from the code and
2. add api endpoint url
3. switch to server side validation by querying api

Switch to server side email validation

---

public/locales/de/translations.json
public/locales/en/translations.json
src/components/forms/BecomeVolunteer/index.tsx

Bug fix.
BecomeVolunteer form now renders error announcement if request response status is non 201

Add non 201 annoucement to volunteer form

---

public/locales/de/translations.json
public/locales/en/translations.json
src/components/Event/EventAccompanying.tsx
src/pages/Subpage.tsx

1. add event component
2. add en and de copies
3. update component call in `Subpage.tsx`

Add accompanying event

---

public/locales/de/translations.json
public/locales/en/translations.json

fix: remove last name

---

src/components/core/button/Button/Button.tsx
src/components/core/image/ImageWithGradient.tsx
src/components/styled/img.tsx

46 fix background image aspect ratio

---

public/locales/de/translations.json
public/locales/en/translations.json
src/components/forms/BecomeVolunteer/FillOrNotify.tsx
src/components/forms/index.css

52 fix layout of modal before volunteer form

---

.github/workflows/deploy.yml

refactor: rename action and delete migration job

---

public/locales/de/translations.json
public/locales/en/translations.json
src/components/core/button/Button/Button.tsx
src/components/core/common/Activities.tsx

90 copy changes on landing page german version

---

src/components/FooterPartners/footer/ContactSocials.tsx
src/components/VolunteeringCategories/Footer.tsx
src/components/VolunteeringOpportunities/Footer.tsx

add: links

---

src/components/Layouts/staticPageLayout/PageWrapper.tsx
src/components/Layouts/staticPageLayout/StaticPageLayout.tsx
src/components/core/WidthLanguageQueryParam.tsx
src/index.css
src/pages/Landing.tsx

136 add language set from url param

---

src/components/forms/AddOpportunity/index.tsx
src/components/forms/utils.ts

update: to more strict number validation

---

src/components/HeaderNew/BurgerMenuItems.tsx
src/components/HeaderNew/Header.tsx
src/components/HeaderNew/MenuItems.tsx
src/components/HeaderNew/MenuitemList.tsx
src/config/types.ts

156 fix event button

---

src/components/forms/BecomeVolunteer/index.tsx

fix: concatenate both lists

---

src/components/OpportunityCards/FiltersButton.tsx
src/config/constants.ts

avoid showing non working button for better UX

Hotfix add opp filter ff

---

public/locales/en/translations.json

Remove /n new line from trans text

---

public/locales/de/translations.json
public/locales/en/translations.json
src/components/forms/AddOpportunity/index.tsx

Added new copy into EN and DE Langauge.
Made the input field as required.
closes #222

222 change copy more information and make it mandatory

---

package.json
yarn.lock

fix: loading dep need4deed-sdk

---

src/components/FooterPartners/footer/ContactSocials.tsx

- Added podcast icon and url
Closes #243

added podcast icon in footer

---

src/components/FooterPartners/footer/ContactSocials.tsx

changes `href` for podcasts to spotify

fix: update podcast link
